In [1]:
import pandas as pd

In [17]:
submission = pd.read_csv('../data/sample_submission.csv')
answer = pd.read_csv('../data/제출해봐야할것.csv')
submission['중식계'] = answer.iloc[:,1]
submission['석식계'] = answer.iloc[:,2]

submission.to_csv('../submission/제출해야될것.csv', index =False)

In [16]:
submission

            일자          중식계         석식계
0   2021-01-27  1006.371593  199.990676
1   2021-01-28   916.657299  426.967676
2   2021-01-29   652.041621  254.959411
3   2021-02-01  1264.357909  493.758240
4   2021-02-02  1063.550042  449.174443
5   2021-02-03  1005.050544  429.808540
6   2021-02-04   960.680613  442.810457
7   2021-02-05   694.717209  350.773965
8   2021-02-08  1269.269612  638.784257
9   2021-02-09  1072.589887  551.869037
10  2021-02-10   775.665185  136.225416
11  2021-02-15  1257.379079  666.685850
12  2021-02-16  1092.501552  613.752978
13  2021-02-17  1056.769019  451.499686
14  2021-02-18   927.179654  501.608533
15  2021-02-19   676.303004  381.896232
16  2021-02-22  1236.497156  640.444765
17  2021-02-23  1056.813690  595.348759
18  2021-02-24   924.055710  430.562253
19  2021-02-25   888.211420  490.547634
20  2021-02-26   630.707370  342.234361
21  2021-03-02  1096.566739  648.400522
22  2021-03-03  1021.499303  426.863579
23  2021-03-04   953.485372  503.159088
24  2021-03-05   692.838350  369.568368
25  2021-03-08  1294.285284  667.835888
26  2021-03-09  1140.918594  662.472672
27  2021-03-10  1033.760982  487.312647
28  2021-03-11   947.125396  494.726557
29  2021-03-12   729.812483  324.577037
30  2021-03-15  1268.651883  677.114152
31  2021-03-16  1057.707919  581.514501
32  2021-03-17  1025.816806  462.372151
33  2021-03-18   926.268407  495.870089
34  2021-03-19   672.635167  289.316344
35  2021-03-22  1245.674164  662.501076
36  2021-03-23  1026.886368  596.473810
37  2021-03-24   912.054158  383.790261
38  2021-03-25   856.149176  497.523068
39  2021-03-26   623.757314  313.735236
40  2021-03-29  1216.765142  668.237349
41  2021-03-30  1017.222134  614.743896
42  2021-03-31   950.765383  417.511264
43  2021-04-01   854.162984  465.574919
44  2021-04-02   652.764083  287.689934
45  2021-04-05  1203.952558  620.583941
46  2021-04-06  1017.374007  565.833430
47  2021-04-07   955.869907  455.221015
48  2021-04-08   857.320542  474.670578
49  2021-04-09   619.367315  295.629853